//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmnRo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmnRo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mIsEXZ7A+wEEAIcpSQ5NEGuvegx+pz6OYYzNccBRcPaCqrtOV+yKyVQz+NooyBgO
        ///fGnHKGr04oPtCwI5g/dZyeSvfC5dHW7tf30NRpB3rFIwKSHQkynmBdpfhPJZHfnH
        ///f7wbytdCrSfA7W/5hFNjyo10n9n/k0c3wvwE3TiyknIz7TqV9JnVWp0vAAUTtAZh
        ///bW5iYW6InAQQAQIABgUCXZ8jawAKCRALh8W68s5W9lQDA/4xnmwuUJ5kVy4QRZHk
        ///NZCJPIQPEF2birAxDiYFKuk1CLonH/fVTIzDAd8Ut/afIHHM4Ob9zSAJG0USYFDu
        ///kkHQd293dK4HpGvgj/Uo7Lb6VTNhxJlCyYVUBWHVv+VAXE22sWuRWhPanrAQQdn7
        ///XdJtT+1wlwmTGixQ4VcWJF0/Rg==.
        /// </summary>
        internal static string AmnBAN_PubKey {
            get {
                return ResourceManager.GetString("AmnBAN-PubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BouncyCastle_Crypto {
            get {
                object obj = ResourceManager.GetObject("BouncyCastle_Crypto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dec4 {
            get {
                object obj = ResourceManager.GetObject("dec4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap enc3 {
            get {
                object obj = ResourceManager.GetObject("enc3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keygen {
            get {
                object obj = ResourceManager.GetObject("keygen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] MaterialSkin {
            get {
                object obj = ResourceManager.GetObject("MaterialSkin", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
